import 'styles/globals.css'
import '@radix-ui/themes/styles.css';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function MyApp({ Component, pageProps }) {
  const getLayout = Component.getLayout || ((page) => page)
  return getLayout(<Component {...pageProps} />)
}